version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/calculator-mcp/main.go
    goos:
      - linux
      - windows
      - darwin

upx:
  - enabled: true
    compress: best
    lzma: true
    brute: true

archives:
  - formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ['zip']
    builds_info:
      mode: 0755

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
